User.create!(username: "Evgeny", password: "password")
User.create!(username: "Jonsnow", password: "password")
User.create!(username: "Arya", password: "password")
User.create!(username: "Frodo", password: "password")
User.create!(username: "Gandalf", password: "password")
